"""A synthetic world of training nodes, for tests and for the demo.

Places speakers at the reference varieties (web/presets.js, generated from
db/05_seed_sites.sql), gives each one an idiolect — the variety's accent
vector plus noise — and a voice (vocal-tract length, pitch, rate), then
synthesises them with the formant synthesiser and stores the WAVs as nodes.

What this can and cannot show. It exercises every line from raw audio to a
posterior on the map, with the true location known, so a wrong answer is a
bug. But the accents are generated by the same assumptions the analyser
measures with, so a good score here is internal consistency — the same caveat
as voice/evaluate.py — not evidence about real speakers.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from ..voice import synth
from ..voice.realisation import Voice
from .featurize import featurize
from .store import NodeStore

PRESETS = Path(__file__).resolve().parents[3] / "web" / "presets.js"
# Dialect surveys elicit a fixed passage (the Speech Accent Archive's "Please
# call Stella", the IViE corpus's "Cinderella") because what is said swamps how
# it is said. Same here: by default every speaker reads the North Wind passage.
PASSAGE = ("northwind",)
ALL_PHRASES = ("northwind", "harvard", "cot_caught", "bath", "bottle", "thirty",
               "goose", "price", "mouth", "face")
# How far an individual drifts from their variety, per feature, as a share of
# the feature's typical range. Idiolect is what the GP nugget ρ is for.
JITTER = {"rhoticity": .08, "npvi_v": 3.0, "pct_v": 1.0, "delta_c": 2.0, "vowel_area": .05,
          "goose_f2": .06, "trap_bath": .06, "low_back_merge": .06, "diph_index": .06,
          "vot_ms": 4.0, "f0_span": .6, "final_rise": .06, "t_glottal": .06, "th_shift": .06}
BOUNDS = {"vot_ms": (5, 120), "npvi_v": (20, 90), "pct_v": (30, 60), "delta_c": (20, 90),
          "vowel_area": (0.3, 1.6), "f0_span": (2, 16)}


def presets(countries: set[str] | None = None) -> list[dict]:
    text = PRESETS.read_text(encoding="utf-8")
    rows = json.loads(text[text.index("["): text.rindex("]") + 1])
    return [r for r in rows if not countries or r["country"] in countries]


def speaker(features: dict[str, float], rng: np.random.Generator) -> tuple[dict, Voice]:
    f = {}
    for k, v in features.items():
        x = v + rng.normal(0.0, JITTER.get(k, 0.0))
        lo, hi = BOUNDS.get(k, (0.0, 1.0))
        f[k] = float(np.clip(x, lo, hi))
    female = rng.random() < 0.5
    voice = Voice(name="synthetic",
                  tract=float(rng.normal(1.17 if female else 1.0, 0.04)),
                  f0_base=float(rng.normal(196.0 if female else 112.0, 12.0)),
                  rate=float(rng.uniform(0.9, 1.1)))
    return f, voice


def populate(store: NodeStore, inventory, countries: set[str] | None = None,
             speakers_per_site: int = 2, clips_per_speaker: int = 1, seed: int = 0,
             phrases: tuple[str, ...] = PASSAGE) -> int:
    """Fill a store. Returns the number of recordings written."""
    rng = np.random.default_rng(seed)
    n = 0
    for site in presets(countries):
        node = store.add_node(site["label"], site["lon"], site["lat"], language="en",
                              node_id=f"node-{site['id']}")
        for s in range(speakers_per_site):
            feats, voice = speaker(site["features"], rng)
            for c in range(clips_per_speaker):
                phrase = phrases[int(rng.integers(len(phrases)))]
                wav = synth.synthesise(phrase, feats, voice=voice,
                                       seed=int(rng.integers(1 << 30))).wav
                store.add_recording(node.id, wav, featurize(wav, inventory),
                                    speaker=f"{site['id']}-{s}")
                n += 1
    return n
