"""Round-trip evaluation: synthesise a variety, then try to recognise it.

This is the reason the voice suite exists. The reference field in
db/05_seed_sites.sql is expert-approximated rather than measured, and a claim
like "Cork has rhoticity 0.75" is otherwise unfalsifiable inside this system.
Generating from that number and measuring what comes back closes the loop:

  * per-feature error says whether `realisation.py` and `accent.py` agree about
    what a parameter *means*;
  * the geolocation error says whether the field as a whole is self-consistent.

A caveat worth stating loudly: passing the round trip proves **internal**
consistency, not correctness against real speakers. The synthesiser and the
analyser share assumptions, so a mistake in both directions cancels. It catches
drift, contradiction and plain bugs; it cannot validate the dialectology.
"""

from __future__ import annotations

import math

import numpy as np

from .. import db, geo, pipeline
from . import synth

# Features that survive a formant synthesiser well enough to be worth scoring.
# The variable rules (t_glottal, th_shift) are generated by rewriting segments,
# so measuring them back tests the recogniser's phone posteriors more than it
# tests the field; they are reported but not scored.
SCORED = ("rhoticity", "npvi_v", "pct_v", "delta_c", "vowel_area",
          "goose_f2", "trap_bath", "low_back_merge", "diph_index",
          "vot_ms", "f0_span")


def site_features(site_id: str) -> dict[str, float]:
    rows = db.query("SELECT key, value FROM site_feature WHERE site_id = %s", (site_id,))
    if not rows:
        raise ValueError(f"no reference features for site {site_id!r}")
    return {r["key"]: float(r["value"]) for r in rows}


def roundtrip(site_id: str, model: geo.SpatialModel, phrase_id: str = "northwind",
              voice: str = "male") -> dict:
    site = db.one("""
        SELECT id, label, country, ST_X(geom) AS lon, ST_Y(geom) AS lat
        FROM accent_site WHERE id = %s
    """, (site_id,))
    if not site:
        raise ValueError(f"unknown site {site_id!r}")

    intended = site_features(site_id)
    made = synth.synthesise(phrase_id, intended, voice=voice)
    got = pipeline.analyse(made.wav, model, language_hint="en")

    measured = {f["key"]: f for f in got["accent"]}
    scale = {f.key: (f.lo, f.hi) for f in model.features}

    rows, errs = [], []
    for key in SCORED:
        want = intended.get(key)
        m = measured.get(key)
        if want is None or m is None or m["value"] is None:
            rows.append({"key": key, "intended": want, "measured": None,
                         "reliability": 0.0, "error": None})
            continue
        lo, hi = scale[key]
        err = abs(m["value"] - want) / (hi - lo)
        rows.append({"key": key, "intended": round(want, 3),
                     "measured": m["value"], "reliability": m["reliability"],
                     "error": round(err, 3)})
        if m["reliability"] > 0.2:
            errs.append(err)

    loc = got.get("location", {})
    km = inside = None
    if loc.get("available"):
        km = _km(site["lon"], site["lat"], loc["map"]["lon"], loc["map"]["lat"])
        inside = _contains(loc["regions"].get("p80"), site["lon"], site["lat"])

    return {
        "site": {"id": site["id"], "label": site["label"], "country": site["country"],
                 "lon": site["lon"], "lat": site["lat"]},
        "phrase": phrase_id,
        "duration_s": round(made.duration_s, 2),
        "features": rows,
        "mean_error": round(float(np.mean(errs)), 4) if errs else None,
        "language": got["language"]["code"],
        "language_confidence": got["language"]["confidence"],
        "geolocation": {
            "available": bool(loc.get("available")),
            "map": loc.get("map"),
            "error_km": None if km is None else round(km, 1),
            "inside_p80": inside,
            "spread_km": loc.get("spread_km"),
            "nearest": [n["label"] for n in loc.get("nearest", [])[:5]],
        },
        "caveats": got.get("caveats", []),
    }


def sweep(model: geo.SpatialModel, language: str = "en", limit: int = 12,
          phrase_id: str = "northwind") -> dict:
    """Round-trip a sample of varieties and summarise.

    Sampled by confidence rather than at random, so the summary reflects the
    varieties the field claims to know best — where a failure is most damning.
    """
    sites = db.query("""
        SELECT id FROM accent_site
        WHERE language = %s ORDER BY confidence DESC, id LIMIT %s
    """, (language, limit))

    results = [roundtrip(r["id"], model, phrase_id) for r in sites]
    errs = [r["mean_error"] for r in results if r["mean_error"] is not None]
    kms = [r["geolocation"]["error_km"] for r in results
           if r["geolocation"]["error_km"] is not None]
    hits = [r["geolocation"]["inside_p80"] for r in results
            if r["geolocation"]["inside_p80"] is not None]

    per_feature: dict[str, list[float]] = {}
    for r in results:
        for row in r["features"]:
            if row["error"] is not None:
                per_feature.setdefault(row["key"], []).append(row["error"])

    return {
        "n": len(results),
        "phrase": phrase_id,
        "mean_feature_error": round(float(np.mean(errs)), 4) if errs else None,
        "median_geolocation_error_km": round(float(np.median(kms)), 1) if kms else None,
        "inside_p80_rate": round(float(np.mean(hits)), 3) if hits else None,
        "worst_features": sorted(
            ({"key": k, "mean_error": round(float(np.mean(v)), 3), "n": len(v)}
             for k, v in per_feature.items()),
            key=lambda d: -d["mean_error"])[:6],
        "results": results,
    }


def _km(lon1, lat1, lon2, lat2) -> float:
    p1, p2 = math.radians(lat1), math.radians(lat2)
    a = (math.sin((p2 - p1) / 2) ** 2
         + math.cos(p1) * math.cos(p2) * math.sin(math.radians(lon2 - lon1) / 2) ** 2)
    return 2 * 6371.0088 * math.asin(math.sqrt(min(1.0, a)))


def _contains(geojson: str | None, lon: float, lat: float) -> bool | None:
    if not geojson:
        return None
    row = db.one("""
        SELECT ST_Contains(ST_GeomFromGeoJSON(%s),
                           ST_SetSRID(ST_MakePoint(%s, %s), 4326)) AS hit
    """, (geojson, lon, lat))
    return bool(row["hit"]) if row else None
