#!/usr/bin/env python3
"""Generate web/presets.js from db/05_seed_sites.sql.

The reference field lives in the SQL seed. Hand-copying a hundred varieties into
JavaScript would guarantee the two drift apart, so the browser's preset list is
generated. Re-run after editing the seed:

    python3 web/build_presets.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SEED = ROOT / "db" / "05_seed_sites.sql"
OUT = Path(__file__).resolve().parent / "presets.js"

COLUMNS = ["id", "label", "lang", "country", "settlement", "lon", "lat", "conf",
           "rhoticity", "npvi_v", "pct_v", "delta_c", "vowel_area", "goose_f2",
           "trap_bath", "low_back_merge", "diph_index", "vot_ms", "f0_span",
           "final_rise", "t_glottal", "th_shift"]

FEATURES = COLUMNS[8:]


def split_row(row: str) -> list[str]:
    out, cur, quoted = [], "", False
    for ch in row:
        if ch == "'":
            quoted = not quoted
            cur += ch
        elif ch == "," and not quoted:
            out.append(cur.strip())
            cur = ""
        else:
            cur += ch
    out.append(cur.strip())
    return out


def value(tok: str):
    if tok.upper() == "NULL":
        return None
    if tok.startswith("'"):
        return tok.strip("'").replace("''", "'")
    return float(tok)


def main() -> None:
    text = SEED.read_text(encoding="utf-8")
    start = text.index("INSERT INTO seed_site VALUES")
    body = text[start:text.index(";", start)]

    rows = []
    for line in body.split("\n"):
        line = line.strip().rstrip(",")
        if not (line.startswith("(") and line.endswith(")")):
            continue
        vals = [value(t) for t in split_row(line[1:-1])]
        if len(vals) != len(COLUMNS):
            continue
        rec = dict(zip(COLUMNS, vals))
        # Only English varieties carry the full vector the synthesiser needs.
        if rec["lang"] != "en" or any(rec[k] is None for k in FEATURES):
            continue
        rows.append({
            "id": rec["id"], "label": rec["label"], "country": rec["country"],
            "lon": rec["lon"], "lat": rec["lat"],
            "features": {k: rec[k] for k in FEATURES},
        })

    rows.sort(key=lambda r: (r["country"], r["label"]))
    payload = json.dumps(rows, indent=1, ensure_ascii=False)
    OUT.write_text(
        "/* GENERATED by web/build_presets.py from db/05_seed_sites.sql — do not edit.\n"
        " * The reference field is expert-approximated from the descriptive\n"
        " * literature, not measured from a corpus. See the README. */\n"
        f"export const PRESETS = {payload};\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} with {len(rows)} varieties")


if __name__ == "__main__":
    main()
